config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  draw :turbo

  # Jumpstart views
  if Rails.env.development? || Rails.env.test?
    mount Jumpstart::Engine, at: "/jumpstart"
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Administrate
  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      if defined?(Sidekiq)
        require "sidekiq/web"
        mount Sidekiq::Web => "/sidekiq"
      end

      resources :announcements
      resources :users do
        resource :impersonate, module: :user
      end
      namespace :user do
        resources :connected_accounts
      end
      resources :accounts
      resources :account_users
      resources :plans
      namespace :pay do
        resources :customers
        resources :charges
        resources :payment_methods
        resources :subscriptions
      end

      root to: "dashboard#show"
    end
  end

  # API routes
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resource :auth
      resource :me, controller: :me
      resource :password
      resources :accounts
      resources :users
      resources :notification_tokens, only: :create
    end
  end

  # User account
  devise_for :users,
    controllers: {
      omniauth_callbacks: "users/omniauth_callbacks",
      registrations: "users/registrations",
      sessions: "users/sessions"
    }
  devise_scope :user do
    get "session/otp", to: "sessions#otp"
  end

  resources :announcements, only: [:index]
  resources :api_tokens
  resources :accounts do
    member do
      patch :switch
    end

    resource :transfer, module: :accounts
    resources :account_users, path: :members
    resources :account_invitations, path: :invitations, module: :accounts
  end
  resources :account_invitations

  # Payments
  resource :billing_address
  namespace :payment_methods do
    resource :stripe, controller: :stripe, only: [:show]
  end
  resources :payment_methods
  namespace :subscriptions do
    resource :billing_address
    namespace :stripe do
      resource :trial, only: [:show]
    end
  end
  resources :subscriptions do
    resource :cancel, module: :subscriptions
    resource :pause, module: :subscriptions
    resource :resume, module: :subscriptions
    resource :upcoming, module: :subscriptions

    collection do
      patch :info
    end

    scope module: :subscriptions do
      resource :stripe, controller: :stripe, only: [:show]
    end
  end
  resources :charges do
    member do
      get :invoice
    end
  end

  namespace :account do
    resource :password
  end
  resources :notifications, only: [:index, :show]
  namespace :users do
    resources :mentions, only: [:index]
  end
  namespace :user, module: :users do
    resource :two_factor, controller: :two_factor do
      get :backup_codes
      get :verify
    end
    resources :connected_accounts
  end

  namespace :action_text do
    resources :embeds, only: [:create], constraints: {id: /[^\/]+/} do
      collection do
        get :patterns
      end
    end
  end

  scope controller: :static do
    get :about
    get :terms
    get :privacy
    get :pricing
  end

  post :sudo, to: "users/sudo#create"

  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  authenticated :user do
    root to: "dashboard#show", as: :user_root
    # Alternate route to use if logged in users should still see public root
    # get "/dashboard", to: "dashboard#show", as: :user_root
  end

  # Public marketing homepage
  root to: "static#index"
end

app/controllers/billing_addresses_controller.rb
class BillingAddressesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_account
  before_action :set_billing_address, only: [:edit, :update, :destroy]

  def new
    @billing_address = current_account.build_billing_address
  end

  def create
    @billing_address = current_account.build_billing_address(billing_address_params)

    if @billing_address.save
      redirect_to subscriptions_path, notice: t("subscriptions.billing_address.created")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @billing_address.update(billing_address_params)
      redirect_to subscriptions_path, notice: t("subscriptions.billing_address.updated")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @billing_address.destroy
    redirect_to subscriptions_path, status: :see_other, notice: t("subscriptions.billing_address.destroyed")
  end

  private

  def billing_address_params
    params.require(:address).permit(:line1, :line2, :city, :state, :country, :postal_code)
  end

  def set_billing_address
    @billing_address = current_account.billing_address
  end
end

app/controllers/subscriptions/billing_addresses_controller.rb
class Subscriptions::BillingAddressesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_current_account_admin
  before_action :set_plan

  layout "checkout"

  def show
  end

  def update
    @billing_address = current_account.billing_address || current_account.build_billing_address
    if @billing_address.update(billing_address_params)
      redirect_to new_subscription_path(plan: @plan.id, step: :payment, promo_code: params[:promo_code])
    else
      render :show, status: :unprocessable_entity
    end
  end

  private

  def set_plan
    @plan = Plan.without_free.find(params[:plan])
  rescue ActiveRecord::RecordNotFound
    redirect_to pricing_path
  end

  def billing_address_params
    params.require(:address).permit(:line1, :line2, :city, :state, :country, :postal_code)
  end
end

app/views/billing_addresses/_form.html.erb
<%= form_with(model: billing_address, url: billing_address_url) do |form| %>
  <%= render "shared/error_messages", resource: form.object %>

  <h5 class="mb-2"><%= t("subscriptions.billing_address.billing_address") %></h5>

  <div class="mb-1">
    <%= form.label :line1, "Address line 1" %>
    <%= form.text_field :line1, class: "form-control" %>
  </div>

  <div class="mb-1">
    <%= form.label :line2, "Address line 2" %>
    <%= form.text_field :line2, class: "form-control" %>
  </div>

  <div class="mb-1">
    <%= form.label :city %>
    <%= form.text_field :city, class: "form-control" %>
  </div>

  <div class="mb-1">
    <%= form.label :state, "State/Province" %>
    <%= form.text_field :state, class: "form-control" %>
  </div>

  <div class="mb-1">
    <%= form.label :postal_code %>
    <%= form.text_field :postal_code, class: "form-control" %>
  </div>

  <div class="mb-1">
    <%= form.label :country %>
    <%= form.country_select :country, include_blank: true %>
  </div>

  <div class="flex justify-between mt-4">
    <%= form.button class: "btn btn-primary" %>
  </div>
<% end %>

app/views/billing_addresses/edit.html.erb
<div class="flex flex-wrap my-4 lg:px-4">
  <div class="w-full mb-4 lg:w-1/4 lg:p-4">
    <%= render partial: "shared/account_navbar" %>
  </div>

  <div class="w-full lg:w-3/4 lg:p-4">
    <div class="lg:p-10 p-4 bg-white rounded-lg border border-gray-200">
      <%= render "form", billing_address: @billing_address %>
    </div>
  </div>
</div>

app/views/billing_addresses/new.html.erb
<div class="flex flex-wrap my-4 lg:px-4">
  <div class="w-full mb-4 lg:w-1/4 lg:p-4">
    <%= render partial: "shared/account_navbar" %>
  </div>

  <div class="w-full lg:w-3/4 lg:p-4">
    <div class="lg:p-10 p-4 bg-white rounded-lg border border-gray-200">
      <%= render "form", billing_address: @billing_address %>
    </div>
  </div>
</div>